---
default_language_version:
  python: python3.10

# yamllint disable rule:indentation
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-added-large-files
  - id: check-docstring-first
  - id: check-json
  - id: check-merge-conflict
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: pretty-format-json
  - id: trailing-whitespace

- repo: https://github.com/psf/black
  rev: 23.9.1
  hooks:
  - id: black

- repo: https://github.com/PyCQA/docformatter
  rev: v1.7.5
  hooks:
    - id: docformatter
      args: ["--in-place", "--blank", "--black", "--close-quotes-on-newline"]

- repo: https://github.com/adrienverge/yamllint
  rev: v1.32.0
  hooks:
    - id: yamllint

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.292
  hooks:
  - id: ruff

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.6.0
  hooks:
  - id: mypy

repos:
- repo: https://github.com/python-poetry/poetry
  rev: 1.6.0
  hooks:
  - id: poetry-check
  